### ISSUE TITLE
Upgrade DSL

### ISSUE THREAD

**Issue by gsuquet** [THipster/THipster#61]
### Feature Spec

Améliorer le DSL (+lexer & parser) afin de prendre en charge les autres fonctionnalités de langage nécessaires à la bonne expression des architectures.

### Use Cases

Créer infrastructure

### Implementation Notes

- [x] Gérer les entrées multilignes --> pipe
- [x] Ajouter la tokénisation des espaces
- [x] Créer une tabulation à partir de 4 espaces uniquement en début de ligne
- [x] Gérer les commentaires
- [x] Ajouter un support pour des listes entre [ ]
- [x] Ajout guillemets simples

### Component

Parser

**Comment by rcattin** [comment]
#101 : Update DSL to allow lists of dictionnaries
